### PR TITLE
24w37a

### LINKED ISSUE #153: Crash on raid end.
**Description**
There is a false in the code where a number should be. Thus it crashes at the end of a raid.

### LINKED ISSUE #154: Add 1.21 wolf variants.
I'm not using MCLA's code due to it being unfinished. I also already got VoxelForge's version done. With the textures per biome working and the texture saving working. 

Edit: Well. I ended up using some, due to the angry eyes stuff.

### LINKED ISSUE #155: Finish up powder snow.
Required for the trial chambers. It has to be done at some point.

### LINKED ISSUE #156: Add MCLA's fractional damage.
#155 depends on this.

### LINKED ISSUE #157: Horse jumping and speed is to much.
Title says it all.

### LINKED ISSUE #158: Occasional crash when attempting to ride horse (again)

### LINKED ISSUE #159: crash in vlf_hunger
```
AsyncErr: Lua: Runtime error from mod 'vlf_mobitems' in callback item_OnSecondaryUse(): ...etest/games/voxelforge/mods/PLAYER/vlf_hunger/hunger.lua:168: attempt to call field 'get_entity_effect_level' (a nil value)
stack traceback:
	...etest/games/voxelforge/mods/PLAYER/vlf_hunger/hunger.lua:168: in function 'eat'
	...etest/games/voxelforge/mods/PLAYER/vlf_hunger/hunger.lua:34: in function <...etest/games/voxelforge/mods/PLAYER/vlf_hunger/hunger.lua:4>
```

### LINKED ISSUE #160: crash in vlf_damage since porting to the new damage api and using healing potion.
AsyncErr: Lua: Runtime error from mod '??' in callback luaentity_Step(): ....minetest/games/voxelforge/mods/CORE/vlf_damage/init.lua:204: attempt to index local 'player' (a nil value)
stack traceback:
	....minetest/games/voxelforge/mods/CORE/vlf_damage/init.lua:204: in function 'heal_player'
	...voxelforge/mods/EFFECTS/vlf_entity_effects/functions.lua:1919: in function 'custom_effect'
	...es/voxelforge/mods/EFFECTS/vlf_entity_effects/splash.lua:156: in function 'on_step_old'
	...mes/voxelforge/mods/ENVIRONMENT/vlf_void_damage/init.lua:17: in function <...mes/voxelforge/mods/ENVIRONMENT/vlf_void_damage/init.lua:16>

### LINKED ISSUE #161: Texture License Change.
@DragonWrangler1 and to everyone. I'm making my own free license for the textures. So you will need to update the licensing accordingly.

### LINKED ISSUE #163: windcharges don't blow out candles
I forgot to add _on_wind_charge_hit function in the candles api. Small, trivial oversight. Pointed out by JoseDouglas on MCLA

### LINKED ISSUE #164: Decorated pots aren't in creative inventory
**Description**
Decorated pots aren't in the creative inventory for some reason

**To Reproduce**
Merely an Example:
Go into the creative inventory.
Search pot.
View the absense of the decorated pots.

**Expected behavior**
The pots should be in the creative inventory.

### LINKED ISSUE #165: dripstone textures missing

### LINKED ISSUE #166: Candles use multiple abms which can downgrade performance.
**Description**
When a bunch of candles are in one area the performance downgrades a lot. Causing a fair amount of lag

**To Reproduce**
Merely an Example:
1. Place a bunch of candles
2. Light them all
3. Wait for a minute
4. try typing /status

**Expected behavior**
I should've made them all into just one abm.

**Desktop**
 - OS: [Ubuntu 23.10]

**Additional context**
The fix is quite trivial and thus will be in the next update.

### LINKED ISSUE #167: mangrove leaves drop unknown items

### LINKED ISSUE #168: Ominous bottles have only one level and are potions.
In MineCraft they have 5 levels and give the player the effect rather than being potions.

### LINKED ISSUE #169: raid captains don't drop ominous bottles, but rather give bad omen effect.
**Description**
See Title.

**To Reproduce**
Merely an Example:
Go to a pillager outpost.
Find a raid captain.
Kill it.
Observe that it gives bad omen

**Expected behavior**
It should drop ominous bottles.

### PR DESCRIPTION
**Pull request by DragonWrangler1**
closes #153
closes #154 
closes #155 
closes #156 
closes #157 
closes #158 
closes #159 
closes #160 
closes #161 
closes #162
closes #163 
closes #164 
closes #165 
closes #166 
closes #167 
closes #168 
closes #169

### CODE REVIEW

File: mods/ENTITIES/mobs_mc/silverfish.lua [hunk 1]
```diff
@@ -61,23 +61,23 @@ vlf_mobs.register_mob("mobs_mc:silverfish", {
...
+	deal_damage = function (self, damage, mcl_reason)
+	    self.health = self.health - damage
+	    if self.health > 0 then
+		-- Potentially summon friends from nearby infested
+		-- blocks unless mob griefing is disabled.
+			if mob_griefing and (mcl_reason.type == "magic" or mcl_reason.direct) then
+				local pos = self.object:get_pos ()
 				local p0 = vector.offset (pos, -10, -5, -10)
 				local p1 = vector.offset (pos, 10, 5, 10)
 				local silverfish_nodes = minetest.find_nodes_in_area (p0, p1, {"group:spawns_silverfish"})
```
Comment (crispiebacon) [inline mods/ENTITIES/mobs_mc/silverfish.lua:73]: Shouldn't this be vlf ?

File: mods/ENTITIES/mobs_mc/wolf.lua [hunk 2]
```diff
@@ -46,11 +176,11 @@ local wolf = {
 	walk_chance = default_walk_chance,
 	walk_velocity = 2,
 	run_velocity = 2.5,
-	damage = 4,
+	damage = 3,
 	reach = 2,
 	attack_type = "dogfight",
 	fear_height = 4,
-	follow = { "vlf_mobitems:bone" },
```
Comment (crispiebacon) [inline mods/ENTITIES/mobs_mc/wolf.lua:53]: Why was the follow table removed ?

File: mods/ITEMS/vlf_sus_stew/init.lua [hunk 3]
```diff
@@ -52,26 +52,26 @@ local function hunger_effect(itemstack, placer, pointed_thing)
 	return itemstack
 end
 
-local function entity_effect_effect(itemstack, placer, pointed_thing,effect)
+local function effect_effect(itemstack, placer, pointed_thing,effect)
```
Comment (crispiebacon) [inline mods/ITEMS/vlf_sus_stew/init.lua:55]: effect_effect ?

File: mods/MAPGEN/vlf_biomes/init.lua [hunk 4]
```diff
@@ -1799,7 +1828,7 @@ local function register_biomes()
 		local biome = overworld_biomes[i]
 
 		-- Deep Ocean
-		minetest.register_biome({
+		--[[minetest.register_biome({
```
Comment (crispiebacon) [inline mods/MAPGEN/vlf_biomes/init.lua:1831]: Any particular reason that this is commented out ?

File: mods/PLAYER/vlf_player/init.lua [hunk 5]
```diff
@@ -207,11 +210,16 @@ minetest.register_globalstep(function(dtime)
...
 			end
+			player:set_sun({texture = "vlf_sun_underwater_sun.png", scale=3.25})
+			player:set_moon({scale=4.25})
 		else
 			if hud_def.hud_id[player_name] then
 				player:hud_remove(hud_def.hud_id[player_name])
 				hud_def.hud_id[player_name] = nil
 			end
+			player:set_sun({texture = "vlf_sun_underwater_sun.png", scale=2.5})
+			player:set_sun({scale=2.5})
```
Comment (crispiebacon) [inline mods/PLAYER/vlf_player/init.lua:221]: why are there two values for setting the sun ?

**Review by crispiebacon — CHANGES_REQUESTED** [review]

**Review by crispiebacon — APPROVED** [review]
Seems to be good.
